### ISSUE TITLE
Membership in pause mode

### ISSUE THREAD

**Issue by bmmcastro** [macbookandrew/cf7-woo-memberships#1]
Hello,
Is there any possibility to a membership add in pause mode and not active?

**Comment by macbookandrew** [comment]
Currently that’s not an option, but if you submit a pull request, I’ll gladly add it!

**Comment by bmmcastro** [comment]
Hello,
I think i add correctly the pull resquest.
Thanks in advance

**Comment by macbookandrew** [comment]
I see an updated readme, but don’t see any change in the actual code?

**Comment by bmmcastro** [comment]
what i have asked was if is possible to you to add this feature. i can pay for it. 
Thanks in advance

**Comment by macbookandrew** [comment]
Gotcha—I was hoping you could code it and I’d add it to the plugin. [Contact me here](https://andrewrminion.com/contact/) with your email address and we can work something out.

**Comment by bmmcastro** [comment]
Contact sended.
waiting for you reply.
Thanks in advance.

**Comment by bmmcastro** [comment]
Did you get my email?
Thanks in advance

**Comment by macbookandrew** [comment]
@bmmcastro Sorry for the delay on this. I just released [v1.3.0](https://github.com/macbookandrew/cf7-woo-memberships/releases/tag/v1.3.0) which includes support for all available membership stati, including any custom ones set using the `wc_memberships_user_membership_statuses` filter.

You’ll need to download, delete the old plugin, upload this version, and reactivate the plugin. I’m also submitting the plugin to the WP plugin directory, so you should get auto-updates in the future once it’s approved.

Please let me know if it works for you, and donate something here if you like it: https://www.paypal.me/AndrewRMinionDesign

Thanks

**Comment by macbookandrew** [comment]
@bmmcastro Looks like the plugin slug changed as a result of getting it on the WP repo, so it **won’t** auto-update.

You can install it from [this link](https://wordpress.org/plugins/cf7-woocommerce-memberships/) or from the **Plugins > Add New** menu item in your WordPress site admin; search for “cf7-woocommerce-memberships”.
